### PR TITLE
fix(design): multi dho layout paddings (#1639)

### LINKED ISSUE #1639: Remove padding at the bottom of container
Summary:
Please remove the padding on the bottom of the container (top is already removed)

image

### PR DESCRIPTION
**Pull request by evgenibir**
### 🗃 Github Issue Or Explanation for this PR. (What is it supposed to do and Why is needed)

Remove padding at the bottom of container #1639

### ✅ Checklist

- Fixed vertical paddings for multi dho layout

close #1639

### CODE REVIEW

File: src/layouts/MultiDhoLayout.vue [hunk 1]
```diff
@@ -257,12 +257,12 @@ q-layout(:style="{ 'min-height': 'inherit' }" :view="'lHr Lpr lFr'" ref="layout"
   q-header.bg-white(v-if="$q.screen.lt.lg")
     top-navigation(:profile="profile" @toggle-sidebar="right = true" @search="onSearch" :dho="dho" :dhos="getDaos($apolloData.data.member)" :selectedDaoPlan="selectedDaoPlan")
   q-page-container.bg-white.window-height.q-py-md(:class="{ 'q-pr-md': $q.screen.gt.md, 'q-px-xs': !$q.screen.gt.md}")
-    .scroll-background.bg-internal-bg.content.full-height
+    .bg-internal-bg.content.full-height
```
Comment (arsenijesavic) [inline src/layouts/MultiDhoLayout.vue:260]: I think you have typo here `.bg-internal-bg.content` you have `-` insted of `.`

Comment (arsenijesavic) [reply src/layouts/MultiDhoLayout.vue:260]: I guess is is supposed to be `.bg-internal.bg-content` ?

**Review by arsenijesavic — APPROVED** [review]
