### PR TITLE
fix(design): loaders for some pages (#1775)

### LINKED ISSUE #1775: Add loading stage for new pages
Summary:
As a DAO user I would like to see the loading icon before a new page loads, so I don't think the page is broken.

AC:
Organization Page: "see all" links for 
- [x] Passed Generic Contributions
- [x] Active Role Assignments
- [x] KPI "Active Assignments"
- [x] KPI "Active Badges"

Homepage / Dashboard:
- [x] KPI "Active Assignments"
- [x] KPI "Active Badges"

Proposal Page:
- [x] Opening Proposal Detail Page

Anywhere else?

Note: same as here:
https://github.com/hypha-dao/dho-web-client/issues/1637

Example:
https://user-images.githubusercontent.com/75991832/199621233-630ad57d-5502-4bc9-8889-55d8f53c669e.mov

### PR DESCRIPTION
**Pull request by evgenibir**
### 🗃 Github Issue Or Explanation for this PR. (What is it supposed to do and Why is needed)

Add loading stage for new pages #1775

### ✅ Checklist

- Fixed display loader in some pages

close #1775

### CODE REVIEW

File: src/pages/proposals/ProposalDetail.vue [hunk 1]
```diff
@@ -645,7 +647,8 @@ export default {
       .bottom-rounded.shadow-up-7.fixed-bottom.z-top(v-if="$q.screen.lt.lg")
         voting(v-if="proposalParsing.status(proposal) !== 'drafted'" :proposal="proposal" :title="null" fixed)
 .proposal-detail.full-width(v-else-if="$q.platform.is.desktop")
-  .row(v-if="!$apollo.queries.proposal") Loading...
+  div(v-if="$apollo.queries.proposal.loading" class="row justify-center q-my-md")
```
Comment (arsenijesavic) [inline src/pages/proposals/ProposalDetail.vue:650]: I suggest you add computed value such as `loading` and for now return just `this.$apollo.queries.proposal.loading` as this page has many moving elements and we can extend other condition for loading easily

**Review by arsenijesavic — APPROVED** [review]
